import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";

import { Container } from "@/shared/components/layouts";
import Footer from "@/shared/components/layouts/footer";
import Header from "@/shared/components/layouts/header";

import "@/styles/globals.css";
import "@/styles/variables.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Theme appearance="light" accentColor="purple">
          <Header />
          <Container>{children}</Container>
          <Footer />
        </Theme>
      </body>
    </html>
  );
}
