import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";

import "@/styles/globals.css";
import "@/styles/variables.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Theme appearance="light" accentColor="purple">
          {children}
        </Theme>
      </body>
    </html>
  );
}
